# Практическое занятие 8
# Компьютерный практикум по алгебре на Python
## Численное решение систем линейных алгебраических уравнений (СЛАУ) с numpy.

https://numpy.org/doc/stable/reference/routines.linalg.html

In [1]:
import numpy as np
from numpy import linalg
from google.colab import files
import pandas as pd

### Задание 1.
Решить СЛАУ с помощью linalg.solve() и выполнить проверку.
$$
\left\{
\begin{matrix}
-x+5y-3z=8\\
4x-y+5z=-1\\
3x+4y+5z=10
\end{matrix}
\right.
$$

In [ ]:
A = np.array([[-1, 5, -3],
              [4, -1, 5],
              [3, 4, 5]])
b = np.array([8, -1, 10])
X = linalg.solve(A, b)
print(f'Решение СЛАУ: {X}')
A @ X == b

Решение СЛАУ: [-1.  2.  1.]


array([ True,  True,  True])

### Задание 2.
Определить с помощью Теоремы Кронекера-Капелли и linalg.matrix_rank, совместна ли СЛАУ
$$
\left\{
\begin{matrix}
-x+5y-3z=8\\
4x-y+5z=-1\\
3x+4y+2z=7
\end{matrix}
\right.
$$

Сделать вывод о числе решений (текстом)

In [ ]:
A = np.array([[-1, 5, -3],
              [4, -1, 5],
              [3, 4, 2]])
b = np.array([8, -1, 7])
Ab = np.column_stack((A, b))
if linalg.matrix_rank(Ab) != linalg.matrix_rank(A):
  print("СЛАУ несовместна")
elif linalg.matrix_rank(Ab) == linalg.matrix_rank(A) and linalg.matrix_rank(A) < A.shape[0]:
  print("СЛАУ является неопределённой")
elif linalg.matrix_rank(Ab) == linalg.matrix_rank(A) == A.shape[0]:
  print("СЛАУ является определённой")

СЛАУ является неопределённой


### Задание 3
В расширенной матрице СЛАУ из Задания 2

1) выделить матрицу левой части

2) выделить столбец правой части

3) транспонировать матрицу, полученную в 1)

4) получить расширенную матрицу из матрицы 3) и столбца 2)

5) создать на основе списочного выражения np.array $3\times 4$ из расположенных в шахматном порядке чисел 1 и $-1$.

In [ ]:
# выделить матрицу левой части
a = Ab[:,:Ab.shape[0]]
a

array([[-1,  5, -3],
       [ 4, -1,  5],
       [ 3,  4,  2]])

In [ ]:
# выделить столбец правой части
bb = Ab[:,Ab.shape[0]:Ab.shape[0]+1]
bb

array([[ 8],
       [-1],
       [ 7]])

In [ ]:
# транспонировать матрицу, полученную в 1)
a_trans = np.transpose(a)
a_trans

array([[-1,  4,  3],
       [ 5, -1,  4],
       [-3,  5,  2]])

In [ ]:
# 4) получить расширенную матрицу из матрицы 3) и столбца 2)
np.column_stack((a_trans, bb))

array([[-1,  4,  3,  8],
       [ 5, -1,  4, -1],
       [-3,  5,  2,  7]])

In [ ]:
# создать на основе списочного выражения np.array  3×4  из расположенных в шахматном порядке чисел 1 и  −1 .
np.array([[(-1)**(i+j) for i in range(4)] for j in range(3)])

array([[ 1, -1,  1, -1],
       [-1,  1, -1,  1],
       [ 1, -1,  1, -1]])

### Задание 4.
Исследовать на совместность СЛАУ с параметром $a$ при значениях параметра $a=-1$, $a=0$ и $a=1$ и найти решение, если оно единственно и провести проверку подстановкой.
$$
\left\{
\begin{matrix}
-x+5y-3z=8a\\
4x-ay+5z=-a\\
3x+4y+2z=5a
\end{matrix}
\right.
$$
**Указание** - описать функцию check_SLAE от аргументов $A$ и $b$ (матрица левой части и столбец правой части), которая возвращает 0 для несовместной СЛАУ, 1 для совместной СЛАУ с единственным решением и 2 в остальных случаях.

Затем в цикле по значениям параметра $a$ проверять с помощью check_SLAE совместность и единственность решения СЛАУ и выводить на экран значение параметра и решение СЛАУ, если оно существует и единственно или "решений нет" или "решение не единственно".

In [3]:
def check_SLAE(A, b):
  Ab = np.column_stack((A, b))
  if linalg.matrix_rank(Ab) > linalg.matrix_rank(A):
    return 0
  elif linalg.matrix_rank(Ab) == linalg.matrix_rank(A) == A.shape[0]:
    return 1
  return 2

a_arr = [-1, 0, 1]
for a in a_arr:
  A = np.array([[-1, 5, -3],
              [4, -1*a, 5],
              [3, 4, 2]])
  b = np.array([8*a, -1*a, 5*a])
  status = check_SLAE(A, b)
  if status==0:
    print(f"При a = {a} СЛАУ не имеет решение")
  elif status == 1:
    print(f"При a = {a} СЛАУ имеет единственное решение")
  else:
    print(f"При a = {a} СЛАУ имеет не единственное решение")

При a = -1 СЛАУ имеет единственное решение
При a = 0 СЛАУ имеет единственное решение
При a = 1 СЛАУ не имеет решение


### Задание 5.
Считать из файла 'SLAE_5.xlsx' матрицу левой части и столбец правой части с листов 'A5' и 'b5' и вывести их на экран.

Решить СЛАУ $AX=b$ и вывести полученное решение на экран.

Записать полученное решение в файл  'SLAE_5.xlsx' на лист 'X5'.

Скачать полученный файл.

In [ ]:
#Считать из файла 'SLAE_5.xlsx' матрицу левой части и столбец правой части с листов 'A5' и 'b5' и вывести их на экран.

uploaded = files.upload()
for file_name in uploaded.keys():
    print(f'Загружен файл {file_name}')

Saving SLAE_5 (1).xlsx to SLAE_5 (1).xlsx
Загружен файл SLAE_5 (1).xlsx


In [ ]:
Adf = pd.read_excel(file_name, sheet_name='A5', header=None)
bdf = pd.read_excel(file_name, sheet_name='b5', header=None)
print(Adf, bdf, sep='\n')

    0  1  2  3
0   6 -3 -1  8
1  -9 -7 -5  9
2   0 -6  5  4
3 -21 -1 -7 -7
    0
0 -15
1 -42
2 -34
3 -44


In [ ]:
# Решить СЛАУ  AX=b  и вывести полученное решение на экран.
A = Adf.to_numpy()
b = bdf.to_numpy()
X = linalg.solve(A, b)
print(X)

[[-4.7]
 [18.8]
 [ 8. ]
 [ 9.7]]


In [ ]:
# Записать полученное решение в файл 'SLAE_5.xlsx' на лист 'X5'.
# Скачать полученный файл.

Xdf = pd.DataFrame(X)
with pd.ExcelWriter(file_name, mode='a') as writer:
    Xdf.to_excel(writer, sheet_name='X5', header=False, index=False)
files.download(file_name)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

### Индивидуальное задание.
Исследовать на совместность СЛАУ с параметром $a$ при заданных значениях параметра $a$ и найти решение, если оно единственно и провести проверку подстановкой.

На листы 'A1', 'A2' и т.п. файла 'Name_Ind_8_SLAE.xlsx' записать матрицы при заданных значениях параметра $a$, на листы 'b1', 'b2' и т.п. столбцы правой части СЛАУ, на листы 'X1', 'X2' и т.п. решения СЛАУ (если оно существует!).


N 21
\begin{align*}
 A = \left[\begin{matrix}0 & 1 & a & -5\\3 & 8 & -5 & 5\\-2 & -7 & -3 & -3\\3 & 5 & 16 & 20\end{matrix}\right],
    \qquad b = \left[\begin{matrix}1\\41\\-42\\47\end{matrix}\right], \alpha = -7, \alpha = -4, \alpha = -1.
 \end{align*}

In [ ]:
prep_df = pd.DataFrame(np.array([0]))
prep_df

0
0  0

In [ ]:
a_arr = [-7, -4, -1]
with pd.ExcelWriter("Buzurukov_21SLAE.xlsx", mode = "w") as writer:
      prep_df.to_excel(writer, sheet_name="A1", header=False, index=False)
for i in range(len(a_arr)):
  a = np.array([[0, 1, a_arr[i], -5],
                [3, 8, -5, 5],
                [-2, -7, -3, -3],
                [3, 5, 16, 20]])
  b = np.array([1, 41, -42, 47])
  status = check_SLAE(a, b)
  Adf = pd.DataFrame(a)
  bdf = pd.DataFrame(b)
  print(a)
  if status == 1:
    X = linalg.solve(a, b)
    Xdf = pd.DataFrame(X)
    with pd.ExcelWriter("Buzurukov_21SLAE.xlsx", mode ="a", if_sheet_exists = 'replace') as writer:
      Adf.to_excel(writer, sheet_name="A"+str(i+1), header=False, index=False)
      bdf.to_excel(writer, sheet_name="b"+str(i+1), header=False, index=False)
      Xdf.to_excel(writer, sheet_name="X"+str(i+1), header=False, index=False)
  else:
    with pd.ExcelWriter("Buzurukov_21SLAE.xlsx", mode = "a", if_sheet_exists = 'replace') as writer:
      Adf.to_excel(writer, sheet_name="A"+str(i+1), header=False, index=False)
      bdf.to_excel(writer, sheet_name="b"+str(i+1), header=False, index=False)
files.download("Buzurukov_21SLAE.xlsx")

[[ 0  1 -7 -5]
 [ 3  8 -5  5]
 [-2 -7 -3 -3]
 [ 3  5 16 20]]
[[ 0  1 -4 -5]
 [ 3  8 -5  5]
 [-2 -7 -3 -3]
 [ 3  5 16 20]]
[[ 0  1 -1 -5]
 [ 3  8 -5  5]
 [-2 -7 -3 -3]
 [ 3  5 16 20]]


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>