In [1]:
import numpy as np
import numpy.linalg
import pandas as pd
from dataclasses import dataclass, field

# Задание

Описать **класс SLAE**

**docstring** """My SLAE Class"""

класс произвольных СЛАУ

**переменные** класса:

***обязательные***

*  name типа str - имя СЛАУ

*  a - матрица левой части, тип np.array

*  b - вектор правой части, тип np.array

***необязательные***

*  var_num число переменных СЛАУ, по умолчанию 0

*  eq_num число уравнений СЛАУ, по умолчанию 0

оба целые числа

**атрибуты**

*  get_a

*  get_b

*  get_var_num

*  get_eq_num

*  get_dim

**методы**

*  set_b

*  set_b_zero

*  x


**Дочерний класс SLAEhomogeneous**

**переменные** класса:

b - вектор правой части, тип np.array со значением по умолчанию None, не должен выводиться на экран при выведении на экран экземпляра класса (хотя в родительском классе уже есть переменная b, здесь ее нужно переопределить, чтобы она стала переменной со значением по умолчанию)

**атрибуты**

*  get_b

**методы**

*  set_b

*  x

**Дочерний класс SLAEsquare**

**переменные** класса:

singular: bool = None

square: bool = None

a_inv

**атрибуты**

is_square

is_singular - возвращает True, если матрица вырождена

get_inv - - возвращает обратную матрицу, если она существует

**метод**


x

**класс SLAE**

**docstring** """My SLAE Class"""

**атрибуты**

*  get_a возвращает матрицу A

*  get_b  возвращает b

*  get_var_num сравнивает var_num с нулем, если 0, то вычисляет число столбцов A и перезаписывает var_num, возвращает var_num

*  get_eq_num аналогично get_var_num дествует с числом уравнений eq_num

*  get_dim возвращает кортеж tulpe из числа уравнений и числа переменных СЛАУ, использует get_eq_num и get_var_num

**методы**

*  set_b проверяет, что передаваемый в качестве аргумента вектор b соответствует матрице a по размерности, после чего перезаписывает значение переменной b экземпляра класса SLAE

*  set_b_zero у этого метода  нет дополнительных аргументов, метод вычисляет, какой размерности должен быть вектор b, составляет вектор из нулей и вызывает set_b

*  x возвращает кортеж, первый элемент True (если решение есть и единственно)  или False (иначе), второй - решение (если есть и единственно) или пустой np.array (np.array([]))

**Дочерний класс SLAEhomogeneous**

**переменные** класса:

b - вектор правой части, тип np.array со значением по умолчанию None, не должен выводиться на экран при выведении на экран экземпляра класса (хотя в родительском классе уже есть переменная b, здесь ее нужно переопределить, чтобы она стала переменной со значением по умолчанию)

**атрибуты**

*  get_b этот атрибут нужно переопределить, чтобы он возвращал вектор из нулей, размерности, соответствуюшей матрице A

**методы**

*  set_b этот метод  нужно переопределить, чтобы он ничего не возвращал и не делал, а только выводил сообщение 'b = 0 in homogeneous SLAE, use get_b instead'

*  x метод проверяет, что матрица квадратная и невырожденная, возвращает в этом случае кортеж с True и нулевым вектором соответствующей размерности, не использует np.linalg.solve,
иначе False и пустой np.array



**Дочерний класс SLAEsquare**

**переменные** класса:

singular: True если вырожденная матрица, иначе False

square: True если квадратная матрица, иначе False

a_inv обратная матрица, если существует, иначе None

**атрибуты**

is_square возвращает square, при необходимости предварительно вычисляя и заполняя эту переменную

is_singular - возвращает singular, при необходимости предварительно вычисляя и заполняя эту переменную

get_inv - - возвращает обратную матрицу, если она существует

**метод**


x проверяет невырожденность матрицы методами этого же класса, для невырожденной матрицы возвращает True и решение или False и  пустой np.array

In [2]:
@dataclass
class SLAE:
    name: str
    a: np.array
    b: np.array
    var_num:int = field(default=0, repr=False)
    eq_num:int = field(default=0, repr=False)

    @property
    def get_a(self) -> np.array:
      return self.a

    @property
    def get_b(self) -> np.array:
      return self.b

    @property
    def get_var_num(self) -> int:
      if self.var_num == 0:
        self.var_num = len(self.a[0])
      return self.var_num

    @property
    def get_eq_num(self) -> int:
      if self.eq_num == 0:
        self.eq_num = len(self.a)
      return self.eq_num

    @property
    def get_dim(self) -> tuple:
      return (self.eq_num, self.get_var_num)

    def set_b(self, b:np.array):
      if len(b) == self.a.shape[0]:
        self.b = b

    def set_b_zero(self):
      self.b = np.zeros(self.a.shape[0])

    def x(self, solver = np.linalg.solve) -> tuple:
      a_matr = self.get_a
      n, m = self.get_a.shape
      res = np.array([])
      if n == m and np.linalg.det(a_matr) != 0:
          res =  solver(a_matr, self.get_b)
      else:
        return (False, res)
      if numpy.linalg.matrix_rank(a_matr) == np.append(a_matr, self.get_b, axis=1) == n:
        return (True, res)
      else:
        return (False, np.array([]))

In [3]:
@dataclass
class SLAEhomogeneous(SLAE):
  b: np.array = field(default=None, repr=False)

  @property
  def get_b(self)-> np.array:
    return np.zeros(len(self.a))

  def set_b(self):
    print("b = 0 in homogeneous SLAE, use get_b instead.")

  def x(self) -> tuple:
    n, m = self.get_a.shape
    if n == m and np.linalg.det(self.get_a) !=0 :
      return (True, np.zeros(n))
    else:
      return (False, np.array([]))

In [31]:
@dataclass
class SLAEsquare(SLAE):
  singular:bool = field(default=None, repr=False)
  square:bool = field(default=None, repr=False)
  a_inv:np.array = field(default=None, repr=False)


  @property
  def is_square(self) -> bool:
    if self.square is None:
      self.set_square()
    return self.square

  @property
  def is_singular(self) -> bool:
    if self.singular is None:
      self.set_singular()
    return self.singular

  @property
  def get_inv(self) -> np.array:
    if self.a_inv is not None:
      return self.a_inv

  def set_singular(self):
    if np.linalg.det(self.get_a)==0:
      self.singular = True
    else:
      self.singular = False
  def set_square(self):
    if self.get_a.shape[0] == self.get_a.shape[1]:
      self.square = True
    else:
      self.square = False
  def set_inv(self):
    try:
      self.a_inv = np.linalg.inv(self.a)
    except:
      self.a_inv = None


  def x(self, solver = np.linalg.solve) -> tuple:
    if self.singular is False and self.square and (self.a_inv is not None):
      res =  solver(self.a, self.b)
      return (True, res)
    return (False, np.array([]))

Считать матрицу и вектор из файла 'ab1.xlsx'

In [6]:
from google.colab import files

file_name = files.upload()

Saving ab1.xlsx to ab1.xlsx


In [7]:
import pandas as pd
A1 = np.array(pd.read_excel(list(file_name.keys())[0], sheet_name='A',header=None))
b1 = np.array(pd.read_excel(list(file_name.keys())[0], sheet_name='b',header=None))

Создать экземпляр класса SLAE с именем 'SLAE_1_1' и матрицей A1, вектором b1, вывести экземпляр на экран

In [8]:
slae1 = SLAE("SLAE_1_1", A1, b1)
slae1

SLAE(name='SLAE_1_1', a=array([[ -3,   5,   5,  10],
       [ -2,  -7,  -3,  -3],
       [  4, -10,   3,   3],
       [ -5,  -9,  10,  -4]]), b=array([[-2],
       [10],
       [10],
       [-7]]))

Вывести на экран атрибуты SLAE_1:

a

get_a

b

get_b

In [9]:
print("a :")
print(slae1.a)
print("get_a :")
print(slae1.get_a)
print("b :")
print(slae1.b)
print("get_b :")
print(slae1.get_b)

a :
[[ -3   5   5  10]
 [ -2  -7  -3  -3]
 [  4 -10   3   3]
 [ -5  -9  10  -4]]
get_a :
[[ -3   5   5  10]
 [ -2  -7  -3  -3]
 [  4 -10   3   3]
 [ -5  -9  10  -4]]
b :
[[-2]
 [10]
 [10]
 [-7]]
get_b :
[[-2]
 [10]
 [10]
 [-7]]


заменить b на вектор из нулей

вывести на экран текущее значение b

In [10]:
slae1.set_b_zero()
slae1.b

array([0., 0., 0., 0.])

заменить b на вектор [4, 5, 6, 7]

вывести на экран текущее значение b

In [11]:
slae1.set_b(np.array([4,5,6,7]))
slae1.b

array([4, 5, 6, 7])

Попытаться заменить b на вектор [-1, 2, -3, 4, 5, 6, 7]

вывести на экран текущее значение b и решение СЛАУ

In [12]:
slae1.set_b(np.array([-1, 2, -3, 4, 5, 6, 7]))
slae1.b

array([4, 5, 6, 7])

Создать экземпляр класса SLAEhomogeneous с именем 'SLAE_homo_1' и матрицей A1, вывести экземпляр на экран

In [13]:
slae1homo = SLAEhomogeneous("SLAE_homo_1" ,A1)
slae1homo

SLAEhomogeneous(name='SLAE_homo_1', a=array([[ -3,   5,   5,  10],
       [ -2,  -7,  -3,  -3],
       [  4, -10,   3,   3],
       [ -5,  -9,  10,  -4]]))


Вывести на экран атрибуты SLAE_homo_1:

a

get_a

In [14]:
print("a :")
print(slae1homo.a)
print("get_a :")
print(slae1homo.get_a)

a :
[[ -3   5   5  10]
 [ -2  -7  -3  -3]
 [  4 -10   3   3]
 [ -5  -9  10  -4]]
get_a :
[[ -3   5   5  10]
 [ -2  -7  -3  -3]
 [  4 -10   3   3]
 [ -5  -9  10  -4]]


вывести на экран текущее значение b

попытаться заменить b на вектор [1, 2, 3, 4, 5, 6, 7]

вывести на экран текущее значение b

In [15]:
print(slae1homo.b)
try:
  slae1homo.set_b(np.array([1, 2, 3, 4, 5, 6, 7]))
except:
  print("error")
print(slae1homo.b)

None
error
None


Создать экземпляр класса SLAEsquare с именем 'SLAE_sq_1' и матрицей A1, вектором b1 вывести экземпляр на экран

Вывести на экран атрибуты SLAE_sq_1:

a

get_a

вывести решение x

In [46]:
slae_square = SLAEsquare("SLAE_sq_1", A1, b1)
print("a :")
print(slae_square.a)
print("get_a :")
print(slae_square.get_a)
print("x: ")
slae_square.set_square()
if slae_square.is_square:
  slae_square.set_singular()
  slae_square.set_inv()
print(slae_square.x())

a :
[[ -3   5   5  10]
 [ -2  -7  -3  -3]
 [  4 -10   3   3]
 [ -5  -9  10  -4]]
get_a :
[[ -3   5   5  10]
 [ -2  -7  -3  -3]
 [  4 -10   3   3]
 [ -5  -9  10  -4]]
x: 
(True, array([[-0.20903955],
       [-1.20106348],
       [-1.45862413],
       [ 1.06713194]]))


заменить b на нулевой вектор


вывести на экран текущее значение b и решение x

попытаться заменить b на вектор [1, 2, 3, 4, 5]

вывести на экран текущее значение b

In [37]:
slae_square.set_b_zero()
print("x if b = zero vector:")
print(slae_square.x())
slae_square.set_b(np.array([1, 2, 3, 4, 5]))
print("x if b = [1, 2, 3, 4, 5]:")
print(slae_square.x())
print("vector b after changing for [1, 2, 3, 4, 5] :")
print(slae_square.b)

x if b = zero vector:
(True, array([-0., -0., -0.,  0.]))
x if b = [1, 2, 3, 4, 5]:
(True, array([-0., -0., -0.,  0.]))
vector b after changing for [1, 2, 3, 4, 5] :
[0. 0. 0. 0.]


Считать матрицу и вектор из файла 'ab2.xlsx'

In [38]:
from google.colab import files

file_name = files.upload()

Saving ab2.xlsx to ab2.xlsx


In [39]:
A2 = np.array(pd.read_excel(list(file_name.keys())[0], sheet_name='A',header=None))
b2 = np.array(pd.read_excel(list(file_name.keys())[0], sheet_name='b',header=None))

Создать экземпляр класса SLAEsquare с именем 'SLAE_sq_2' и матрицей A2, вектором b2 вывести экземпляр на экран

Вывести на экран атрибуты SLAE_sq_2:

a

get_a

вывести решение x

In [47]:
slae_square2 = SLAEsquare("SLAE_sq_2", A2, b2)
print("a :")
print(slae_square2.a)
print("get_a :")
print(slae_square2.get_a)
print("x: ")
slae_square2.set_square()
if slae_square2.is_square:
  slae_square2.set_singular()
  slae_square2.set_inv()
print(slae_square2.x())

a :
[[ -3   5   5  10]
 [ -2  -7  -3  -3]
 [  4 -10   3   3]
 [ -5  -9  10  -4]
 [ -4  -8  11  -3]
 [ -3  -7  12  -2]]
get_a :
[[ -3   5   5  10]
 [ -2  -7  -3  -3]
 [  4 -10   3   3]
 [ -5  -9  10  -4]
 [ -4  -8  11  -3]
 [ -3  -7  12  -2]]
x: 
(False, array([], dtype=float64))


заменить b на нулевой вектор


вывести на экран текущее значение b и решение x

попытаться заменить b на вектор [1, 2, 3, 4, 5, 6]

вывести на экран текущее значение b

In [48]:
slae_square2.set_b_zero()
print("x if b = zero vector:")
print(slae_square2.x())
slae_square2.set_b(np.array([1, 2, 3, 4, 5, 6]))
print("x if b = [1, 2, 3, 4, 5, 6]:")
print(slae_square2.x())
print("vector b after changing for [1, 2, 3, 4, 5, 6] :")
print(slae_square2.b)

x if b = zero vector:
(False, array([], dtype=float64))
x if b = [1, 2, 3, 4, 5, 6]:
(False, array([], dtype=float64))
vector b after changing for [1, 2, 3, 4, 5, 6] :
[1 2 3 4 5 6]
